[tool.poetry]
name = "mysite"
version = "0.1.0"
description = "Projeto django - Tutorial"
authors = ["Vinícius Melo <vinimmelo.dev@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.0.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
